    call npm install @angular/animations --save
    call npm install @angular/common --save
    call npm install @angular/compiler --save
    call npm install @angular/compiler-cli --save
    call npm install @angular/core --save
    call npm install @angular/forms --save
    call npm install @angular/http --save
    call npm install @angular/platform-browser --save
    call npm install @angular/platform-browser-dynamic --save
    call npm install @angular/platform-server --save
    call npm install @angular/router --save
    call npm install @nguniversal/express-engine --save
    call npm install angular2-highcharts --save
    call npm install angular2-markdown --save
    call npm install core-js --save
    call npm install express --save
    call npm install ejs --save
    call npm install marked --save
    call npm install rxjs --save
    call npm install xhr2 --save
    call npm install zone.js --save
