    call npm install @ngtools/webpack --save-dev
    call npm install @types/express --save-dev
    call npm install @types/marked --save-dev
    call npm install @types/node --save-dev
    call npm install @types/underscore --save-dev
    call npm install compression --save-dev
    call npm install copy-webpack-plugin --save-dev
    call npm install css-loader --save-dev
    call npm install extract-text-webpack-plugin --save-dev
    call npm install jasmine-core --save-dev
    call npm install karma --save-dev
    call npm install karma-chrome-launcher --save-dev
    call npm install karma-jasmine --save-dev
    call npm install karma-jasmine-html-reporter --save-dev
    call npm install karma-sourcemap-loader --save-dev
    call npm install karma-webpack --save-dev
    call npm install file-loader --save-dev
    call npm install html-webpack-plugin --save-dev
    call npm install node-sass --save-dev
    call npm install nodemon --save-dev
    call npm install raw-loader --save-dev
    call npm install rimraf --save-dev
    call npm install sass-loader --save-dev
    call npm install script-ext-html-webpack-plugin --save-dev
    call npm install style-loader --save-dev
    call npm install typescript --save-dev
    call npm install tslint --save-dev
    call npm install underscore --save-dev

    call npm install webpack --save-dev
    call npm install webpack-dev-server --save-dev
    call npm install webpack-merge --save-dev
