pipeline {
    agent any 

    stages {
        stage('Build') { 
            steps { 
                sh 'echo coucou' 
            }
        }
        stage('Test'){
            steps {
                sh 'echo "run karma tests"' 
            }
        }
        stage('Packaging'){
            steps {
                sh 'docker build -f Dockerfile  .' 
            }
        }
        stage('tag') {
            steps {
                sh 'echo "docker tag mainModule:latest"'
            }
        }
        stage('push') {
            steps {
                sh 'echo "docker push mainModule:latest"'
            }
        }
    }
}